version: '3'

services:
  workhours:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - workhours_data:/data
    environment:
      - DATABASE_LOCATION=/data/workhours.db
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    restart: unless-stopped

volumes:
  workhours_data:
    driver: local